spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/university
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 06021988abc

  thymeleaf:
    encoding: UTF-8
    prefix: /WEB-INF/views/
    suffix: .html

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: validate