spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/university
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 06021988abc
    hikari:
      maximum-pool-size: 50

  thymeleaf:
    encoding: UTF-8
    prefix: /WEB-INF/views/
    suffix: .html

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect